### ISSUE TITLE
won't create database

### ISSUE THREAD

**Issue by fahmird** [psztrnk/catalog#3]
i have a problem when creating database it says:
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\catalog-master\config\configure.php:28 Stack trace: #0 {main} thrown in C:\xampp\htdocs\catalog-master\config\configure.php on line 28

Could you help me?

**Comment by psztrnk** [comment]
Hi fahmird,

sorry for the long-long wait, I somehow unsubscribed from all the notifications of my own repo. :(
Anyways: this was caused by the total deprecation of the mysql_* function as of PHP 7.0.0. The config file is updated to use the mysqli function.
I successfully tested it on localhost with PHP 7.4.4 and MariaDB 10.4.11. Any test on your setup would be appreciated.

Thanks.
